### ISSUE TITLE
Does not work on Windows 10

### ISSUE THREAD

**Issue by silbinarywolf** [myitcv/gjbt#19]
**The problem**

- Chrome when installed on Windows doesn't add itself to the %PATH%, As a Windows user, you would expect it to just "be found" at this location or similar:
```
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
```

- Even when manually adding that path to the `Path` environment variable (not a typo, on Windows 10, its called Path, all lowercase) and creating a copy of chrome.exe being renamed to google-chrome, it did not work.

**The hacky fix**
I simply hardcoded the default paths like so and running `GOOS=linux gjbt --bench=.` worked!
```
	fBinary = flag.String("binary", "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe", "path to Chrome binary")
	fDriver = flag.String("driver", "D:\\ChromeDriver\\chromedriver.exe", "path to chromedriver binary")
```

**A future / better solution**
I'll see if I can put together a PR in the next few days to improve support on Windows 10. I'll investigate whether it can't find "Path" due to the underlying exec.LookPath checking the envvar "path". (case sensitive issue possibly?)

Also I'll make the default chrome exe name "chrome.exe for Windows builds.

**Comment by myitcv** [comment]
Do the two flags not work for you?

**Comment by silbinarywolf** [comment]
No they weren't working for some reason. I'll see if I can investigate as to why that is today first.

**Comment by silbinarywolf** [comment]
@myitcv The two flags do work. I must have been using them incorrectly or something.
So this works successfully on my machine:
```
gjbt --bench=. --binary="C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --driver="D:\ChromeDriver\chromedriver.exe"
```

However, I added both folders for ChromeDriver and Google Chrome to my PATH and it's unable to pick those up, so I'll investigate further and determine what the problem is.

**Comment by silbinarywolf** [comment]
Looks like the updates to my PATH weren't taking for whatever reason until I restarted my computer. I'm guessing Windows kept a Git Bash terminal hanging around that I wasn't seeing, which would mean my PATH never reloaded when I opened "new" terminal consoles.

**Comment by silbinarywolf** [comment]
@myitcv Would you be open to a PR that:
- Changes `fBinary` to use `chrome` instead of "google-chrome" on Windows. (as that is the binary name)
or preferably:
- Looks for Chrome in its usual install location if you didn't configure with the --binary flag.
  - Windows 7: C:\Program Files (x86)\Google\Application\chrome.exe
    - Source: https://stackoverflow.com/questions/17736215/universal-path-to-chrome-exe

**Comment by silbinarywolf** [comment]
Closing this as this `gjbt` does work on Windows!
Added PR here: https://github.com/myitcv/gjbt/pull/20
