### ISSUE TITLE
Error message is not friendly

### ISSUE THREAD

**Issue by hajimehoshi** [myitcv/gjbt#2]
```
$ gjbt .
FAIL    github.com/hajimehoshi/ebiten   1.395s
warning: system calls not available, see https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md
```

I understand syscall is not available, but would it be possible to have a better error message to know where syscall is used?

**Comment by myitcv** [comment]
Possibly, yes. These requirements come about as a result of `gopherjs test` having these requirements. So I don't think we can avoid them. But yes, we should document that better.

Will leave this open to track that.

**Comment by hajimehoshi** [comment]
Thanks. Even after fixing the syscall problem, test failure details are not shown...

```
$ gjbt .
FAIL    github.com/hajimehoshi/ebiten   1.489s
```

**Comment by myitcv** [comment]
Hmm, that's interesting. If I deliberately introduce a failure into `myitcv.io/react` I do get some output:

```
$ gjbt myitcv.io/react
FAIL    myitcv.io/react 0.615s
--- FAIL: TestFail (0.01s)
        <anonymous>:38088: This should fail
FAIL
```

Do you have a commit pushed up somewhere that I can help debug this?

**Comment by hajimehoshi** [comment]
I think you can test

```
$ gjbt github.com/hajimehoshi/ebiten
```

with the latest Ebiten. Thanks!

**Comment by myitcv** [comment]
Using these commits:

```
$ (command cd $(go list -f '{{.Dir}}' github.com/hajimehoshi/ebiten); git rev-parse HEAD)
81a1fd47447714ed4cb28d0b47644866c40754d7
$ (command cd $(go list -f '{{.Dir}}' github.com/gopherjs/gopherjs); git rev-parse HEAD)
8dffc02ea1cb8398bb73f30424697c60fcf8d4c5
$ (command cd $(go list -f '{{.Dir}}' myitcv.io/gjbt); git rev-parse HEAD)
ff72e04c3c6f2769923b8a4048284b718ac3be1f
```

I get a passing set of tests:

```
$ gjbt github.com/hajimehoshi/ebiten
ok      github.com/hajimehoshi/ebiten   28.827s
PASS
```

**Comment by hajimehoshi** [comment]
> `$ (command cd $(go list -f '{{.Dir}}' myitcv.io/gjbt); git rev-parse HEAD)`

Interesting, I installed `go get github.com/myitcv/gjbt`...

**Comment by hajimehoshi** [comment]
Hmm, I'm using all the same version, but it still fails...

**Comment by hajimehoshi** [comment]
```
$ chromedriver -v
ChromeDriver 2.38.552518 (183d19265345f54ce39cbb94cf81ba5f15905011)
```

Is this the correct version?

**Comment by myitcv** [comment]
I'm using the version shown in https://github.com/myitcv/gjbt/blob/master/.travis.yml

Maybe you're seeing an issue related to https://github.com/sclevine/agouti/issues/156?

Thanks for the PR - will look when I'm back
