### ISSUE TITLE
Fails to go-get gjbt on MacBook Pro

### ISSUE THREAD

**Issue by hajimehoshi** [myitcv/gjbt#21]
```
$ go get -u myitcv.io/gjbt
package myitcv.io/gjbt: cannot find package "myitcv.io/gjbt" in any of:
        /usr/local/go/src/myitcv.io/gjbt (from $GOROOT)
        /Users/hajimehoshi/go/src/myitcv.io/gjbt (from $GOPATH)
```

**Comment by hajimehoshi** [comment]
I read myitcv.io/gjbt:

```
<!DOCTYPE html>
<html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta name="go-import" content="myitcv.io git https://github.com/myitcv/x">

        <meta name="go-source" content="myitcv.io https://github.com/myitcv/x/wiki https://github.com/myitcv/x/tree/master{/dir} https://github.com/myitcv/x/blob/master{/dir}/{file}#L{line}">
        <meta http-equiv="refresh" content="0; url=https://godoc.org/myitcv.io/gjbt">
</head>
<body>
Redirecting to docs at <a href="https://godoc.org/myitcv.io/gjbt">godoc.org/myitcv.io/gjbt</a>...
</body>
</html>
```
so I thought there should be gjbt repository at https://github.com/myitcv/x, but not.

https://github.com/myitcv/x/commit/bf2c84553c7827a1cb6cecf19424fdb93b887d5b doesn't include gjbt?

**Comment by myitcv** [comment]
@hajimehoshi apologies, I've migrated everything to a mono repo in preparation for go module support; `gjbt` is one of the packages that has moved import path in the process. 

There's no easy way around this unfortunately (and I don't have a good way of telling users that things are going to happen).

The new package location is:

```
myitcv.io/cmd/gjbt
```

Apologies for the trouble.
